// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webcofflatteshop.Data;

#nullable disable

namespace webcofflatteshop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529171415_Addproductnew")]
    partial class Addproductnew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webcofflatteshop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Matcha"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bakery"
                        });
                });

            modelBuilder.Entity("webcofflatteshop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đậm đà vị cà phê Ý nguyên bản.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Espresso",
                            Price = 2.50m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Espresso pha loãng, nhẹ nhàng và thơm.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Americano",
                            Price = 3.00m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bọt sữa mịn, cân bằng giữa sữa và cà phê.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Cappuccino",
                            Price = 3.80m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sữa béo mượt cùng espresso dịu êm.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Latte",
                            Price = 4.20m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hòa quyện cà phê và chocolate ngọt ngào.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Mocha",
                            Price = 4.50m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vị caramel thơm, hậu vị espresso mạnh.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Caramel Macchiato",
                            Price = 4.90m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ủ lạnh 18 tiếng, mượt và ít chua.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Cold Brew",
                            Price = 4.30m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cà phê sữa đá đậm vị Việt Nam.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Vietnamese Iced Coffee",
                            Price = 3.70m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trà xanh Nhật kết hợp sữa thanh dịu.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Matcha Latte",
                            Price = 4.60m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đá xay chocolate mát lạnh cho ngày hè.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Chocolate Frappe",
                            Price = 5.20m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bánh sừng bò bơ giòn tan mỗi sáng.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Croissant Butter",
                            Price = 2.90m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bánh tiramisu mềm mịn thơm cà phê.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Tiramisu",
                            Price = 4.10m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cheesecake béo nhẹ phủ mứt việt quất.",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Blueberry Cheesecake",
                            Price = 4.80m,
                            UpdatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("webcofflatteshop.Models.Product", b =>
                {
                    b.HasOne("webcofflatteshop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("webcofflatteshop.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
