// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webcofflatteshop.Data;

#nullable disable

namespace webcofflatteshop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529020310_UpdateCategory2")]
    partial class UpdateCategory2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webcofflatteshop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Matcha"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bakery"
                        });
                });

            modelBuilder.Entity("webcofflatteshop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Đậm đà vị cà phê Ý nguyên bản.",
                            Name = "Espresso",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Espresso pha loãng, nhẹ nhàng và thơm.",
                            Name = "Americano",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Bọt sữa mịn, cân bằng giữa sữa và cà phê.",
                            Name = "Cappuccino",
                            Price = 3.80m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Sữa béo mượt cùng espresso dịu êm.",
                            Name = "Latte",
                            Price = 4.20m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Hòa quyện cà phê và chocolate ngọt ngào.",
                            Name = "Mocha",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Vị caramel thơm, hậu vị espresso mạnh.",
                            Name = "Caramel Macchiato",
                            Price = 4.90m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Ủ lạnh 18 tiếng, mượt và ít chua.",
                            Name = "Cold Brew",
                            Price = 4.30m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Cà phê sữa đá đậm vị Việt Nam.",
                            Name = "Vietnamese Iced Coffee",
                            Price = 3.70m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Trà xanh Nhật kết hợp sữa thanh dịu.",
                            Name = "Matcha Latte",
                            Price = 4.60m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Đá xay chocolate mát lạnh cho ngày hè.",
                            Name = "Chocolate Frappe",
                            Price = 5.20m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Bánh sừng bò bơ giòn tan mỗi sáng.",
                            Name = "Croissant Butter",
                            Price = 2.90m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Bánh tiramisu mềm mịn thơm cà phê.",
                            Name = "Tiramisu",
                            Price = 4.10m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Cheesecake béo nhẹ phủ mứt việt quất.",
                            Name = "Blueberry Cheesecake",
                            Price = 4.80m
                        });
                });

            modelBuilder.Entity("webcofflatteshop.Models.Product", b =>
                {
                    b.HasOne("webcofflatteshop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("webcofflatteshop.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
